"""Two-page clinical PDF report generation."""
from __future__ import annotations
import base64, io
from datetime import datetime
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image, PageBreak
from reportlab.lib.enums import TA_CENTER

def generate_pdf_report(patient_data, prediction_results) -> bytes:
    b = io.BytesIO()
    doc = SimpleDocTemplate(b, pagesize=A4, rightMargin=15*mm, leftMargin=15*mm, topMargin=14*mm, bottomMargin=14*mm)
    styles = getSampleStyleSheet()
    styles["Title"].alignment = TA_CENTER
    story = [Paragraph("LUNGINSIGHT — MULTIMODAL CLINICAL INFERENCE", styles["Title"]),
             Paragraph("CONFIDENTIAL • Decision-support report — not a standalone diagnosis", styles["Normal"]), Spacer(1, 5*mm)]
    story.append(Paragraph(f"<b>Patient ID:</b> {patient_data.get('patient_id','Not supplied')} &nbsp;&nbsp; <b>Generated:</b> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", styles["Normal"]))
    rows = [["Clinical variable", "Value"]]
    for k, v in patient_data.items():
        if k != "patient_id": rows.append([k, "Missing" if v in (None, "") else str(v)])
    t = Table(rows, colWidths=[75*mm, 95*mm]); t.setStyle(TableStyle([("BACKGROUND",(0,0),(-1,0),colors.HexColor("#1f2937")),("TEXTCOLOR",(0,0),(-1,0),colors.white),("GRID",(0,0),(-1,-1),0.25,colors.grey),("VALIGN",(0,0),(-1,-1),"TOP")]))
    story += [Paragraph("Baseline Clinical Inputs", styles["Heading2"]), t, Spacer(1, 4*mm)]
    stage = prediction_results.get("stage", {})
    hist = prediction_results.get("histology", {})
    surv = prediction_results.get("survival", {})
    summary = [[Paragraph("<b>Predicted Stage</b>", styles["Normal"]), Paragraph("<b>Confidence</b>", styles["Normal"]), Paragraph("<b>Histology</b>", styles["Normal"])],
               [str(stage.get("label","Unavailable")), f"{stage.get('positive_probability',0)*100:.1f}%" if stage.get("positive_probability") is not None else "N/A", str(hist.get("label") or "Unavailable")]]
    st = Table(summary, colWidths=[55*mm, 55*mm, 60*mm]); st.setStyle(TableStyle([("BACKGROUND",(0,0),(-1,0),colors.HexColor("#dbeafe")),("BOX",(0,0),(-1,-1),0.8,colors.HexColor("#334155")),("GRID",(0,0),(-1,-1),0.25,colors.grey),("ALIGN",(0,0),(-1,-1),"CENTER"),("FONTSIZE",(0,0),(-1,-1),10)]))
    story += [Paragraph("Diagnostic Summary", styles["Heading2"]), st, Spacer(1, 5*mm)]
    if prediction_results.get("imaging", {}).get("representative_slice"):
        raw = base64.b64decode(prediction_results["imaging"]["representative_slice"].split(",",1)[-1])
        story += [Paragraph("Representative CT Slice", styles["Heading2"]), Image(io.BytesIO(raw), width=75*mm, height=75*mm), Spacer(2,mm)]
    story.append(Paragraph("Risk & Interpretability", styles["Heading2"]))
    story.append(Paragraph(f"Estimated partial hazard / risk score: <b>{surv.get('risk_score','Unavailable')}</b>. Estimated median survival: <b>{surv.get('median_survival_months','Unavailable')} months</b>.", styles["Normal"]))
    shap = prediction_results.get("shap", {})
    for title, vals in [("Positive risk contributions", shap.get("positive", [])), ("Negative risk contributions", shap.get("negative", []))]:
        story.append(Paragraph(title, styles["Heading3"]))
        story.append(Paragraph("<br/>".join(f"• {n}: {v:+.4f}" for n,v in vals) or "Unavailable", styles["Normal"]))
    if shap.get("plot_base64"):
        story.append(Image(io.BytesIO(base64.b64decode(shap["plot_base64"])), width=170*mm, height=95*mm))
    story.append(PageBreak())
    story += [Paragraph("Survival Trajectory & Review", styles["Heading2"])]
    if surv.get("times_months"):
        story.append(Paragraph(f"Survival curve points: {len(surv['times_months'])}. The curve is generated by the fitted survival model.", styles["Normal"]))
    story += [Spacer(1, 20*mm), Paragraph("Reviewing Oncologist / Pathologist: ________________________________", styles["Normal"]),
              Spacer(1, 8*mm), Paragraph("Signature: __________________________________  Date: _______________", styles["Normal"]),
              Spacer(1, 15*mm), Paragraph("<b>Clinical disclaimer:</b> This report is generated by an AI decision-support system from supplied clinical and imaging inputs. It is not a diagnosis, does not replace radiology/pathology review or clinical judgment, and must be independently verified by qualified healthcare professionals.", styles["Normal"])]
    doc.build(story)
    return b.getvalue()
